CREATE SCHEMA ESTC_I;
USE ESTC_I;

#--------------------TABELA DE FORNECEDORES--------------------

CREATE TABLE IF NOT EXISTS FORNECEDORES(
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT NOT NULL,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL
);

#--------------------TABELA DE FILIAIS--------------------

CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAL_COD INT PRIMARY KEY,
FILIAL_NOME VARCHAR(45) NOT NULL,
FILIAL_RUA VARCHAR(100) NOT NULL,
FILIAL_NUMRUA INT NOT NULL,
FILIAL_BAIRRO VARCHAR(50) NOT NULL,
FILIAL_CIDADE VARCHAR(50) NOT NULL,
FILIAL_ESTADO VARCHAR(50) NOT NULL,
FILIAL_PAIS VARCHAR(50) NOT NULL,
FILIAL_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAL_CAPACIDADE TEXT NOT NULL
);

#--------------------TABELA DE PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQ_MIN DECIMAL(10,3) NOT NULL
);

#--------------------TABELA DE PEDIDOS--------------------

CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_CODIGO INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL, #NOSSA CHAVE ESTRANGEIRA DE FORNECEDOR
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO APELIDO CH.ESTRANGEIRA(CAMPO CRIADO) REFERENCIA TABELA(CH.PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO(CONSTRAINT) É UMA BOA PRÁTICA
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

#--------------------TABELA DE RECEBIMENTOS--------------------

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANT_PROD DECIMAL(10,3),
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY(RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO));

#--------------------ASSOCIATIVA ENTRE PEDIDOS E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PDPR_PEDIDOS, PDPR_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS) REFERENCES PEDIDOS(PED_CODIGO),
CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#--------------------ASSOCIATIVA ENTRE FILIAIS E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAL INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FLPR_FILIAL,FLPR_PRODUTOS),
FLPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAL) REFERENCES FILIAIS(FILIAL_COD),
CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

#--------------------ASSOCIATIVA ENTRE FORNECEDORES E PRODUTOS--------------------

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR) REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) REFERENCES PRODUTOS(PROD_COD)
);

-- DML'S PARA A TABELA CLIENTES
INSERT INTO CLIENTES (CLI_CPF, CLI_NOME, CLI_RUA, CLI_NUMRUA, CLI_BAIRRO, CLI_CIDADE, CLI_UF, CLI_PAIS, CLI_CEP, CLI_STATUS_PROMO) VALUES ('12345678901', 'João Silva', 'Rua A', '123', 'Centro', 'São Paulo', 'SP', 'Brasil', '01000-000', 'APROVADO'), ('10987654321', 'Maria Oliveira', 'Rua B', '456', 'Jardim', 'Rio de Janeiro', 'RJ', 'Brasil', '20000-000', 'REPROVADO'); 
UPDATE CLIENTES SET CLI_STATUS_PROMO = 'REPROVADO' WHERE CLI_CPF = '12345678901'; 

-- DML'S PARA A TABELA FORNECEDORES
INSERT INTO FORNECEDORES (FORN_CNPJ, FORN_NOME, FORN_TELEFONE, FORN_EMAIL) VALUES ('12.345.678/0001-90', 'Fornecedor A', '(11) 91234-5678', 'fornecedorA@example.com'), ('98.765.432/0001-00', 'Fornecedor B', '(21) 98765-4321', 'fornecedorB@example.com'); 
UPDATE FORNECEDORES SET FORN_TELEFONE = '(11) 99876-5432' WHERE FORN_CNPJ = '12.345.678/0001-90'; 

-- DML'S PARA A TABELA PRODUTOS
INSERT INTO PRODUTOS (PROD_ID, PROD_CATEGORIA, PROD_QTDDISPONIVEL, PROD_PRECO) VALUES (1, 'Eletrônicos', 50, 999.99), (2, 'Móveis', 30, 199.99); 
UPDATE PRODUTOS SET PROD_PRECO = 899.99 WHERE PROD_ID = 1; 

-- DML'S PARA A TABELA PAGAMENTOS
INSERT INTO PAGAMENTOS (PAG_ID, PAG_DATA, PAG_HORA, PAG_VALOR, PAG_STATUS) VALUES (1, '2024-01-01', '12:00:00', 999.99, 'PENDENTE'), (2, '2024-01-02', '14:30:00', 199.99, 'PAGO'); 
UPDATE PAGAMENTOS SET PAG_STATUS = 'CANCELADO' WHERE PAG_ID = 1; 

-- DML'S PARA A TABELA VENDAS
INSERT INTO VENDAS (VENDA_ID, CLI_CPF, PAG_ID) VALUES (1, '12345678901', 1), (2, '10987654321', 2); 
UPDATE VENDAS SET PAG_ID = 2 WHERE VENDA_ID = 1; 

-- DML'S PARA A TABELA VENDAS_PRODUTOS
INSERT INTO VENDAS_PRODUTOS (VENDA_ID, PROD_ID, VEPRO_QTD_VENDIDA, VEPRO_VALORTOTAL) VALUES (1, 1, 1, 999.99), (2, 2, 2, 399.98); 
UPDATE VENDAS_PRODUTOS SET VEPRO_QTD_VENDIDA = 2, VEPRO_VALORTOTAL = 1999.98 WHERE VENDA_ID = 1 AND PROD_ID = 1; 
