#CRIANDO O BANCO DE DADOS
CREATE SCHEMA EMPRESA_AEREA;

#USANDO O BANCO DE DADOS
USE EMPRESA_AEREA;


#--------------------TABELA DE PASSAGEIROS--------------------
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF VARCHAR(14) PRIMARY KEY,
    PASS_NOME VARCHAR(50) NOT NULL,
    PASS_TELEFONE VARCHAR(15) NOT NULL,
    PASS_RUA VARCHAR(100) NOT NULL,
    PASS_NUMRUA INT,
    PASS_BAIRRO VARCHAR(50) NOT NULL,
    PASS_CIDADE VARCHAR(50) NOT NULL,
    PASS_ESTADO VARCHAR(50) NOT NULL,
    PASS_PAIS VARCHAR(50) NOT NULL,
    PASS_CODPOSTAL VARCHAR(10) NOT NULL,
    PASS_EMAIL VARCHAR(50) NOT NULL
);

#--------------------TABELA DE FUNCIONARIOS--------------------

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_CPF VARCHAR(14) NOT NULL,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,
    FUNC_RUA VARCHAR(100) NOT NULL,
    FUNC_NUMRUA INT,
    FUNC_BAIRRO VARCHAR(50) NOT NULL,
    FUNC_CIDADE VARCHAR(50) NOT NULL,
    FUNC_ESTADO VARCHAR(50) NOT NULL,
    FUNC_PAIS VARCHAR(50) NOT NULL,
    FUNC_CODPOSTAL VARCHAR(10) NOT NULL
);

#--------------------TABELA DE AERONAVES--------------------

CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO VARCHAR(10) PRIMARY KEY,
    AERON_MODELO VARCHAR(50) NOT NULL,
    AERON_FABRICANTE VARCHAR(50) NOT NULL,
    AERON_ANOFABR YEAR NOT NULL,
    AERON_CAPACIDADE TEXT NOT NULL,
    AERON_AUTONOMIA VARCHAR(10) NOT NULL
);

#--------------------TABELA DE AEROPORTOS--------------------

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_CODIGO INT PRIMARY KEY,
    AEROP_NOME VARCHAR(50) NOT NULL,
    AEROP_CIDADE VARCHAR(50) NOT NULL,
    AEROP_PAIS VARCHAR(50) NOT NULL,
    AEROP_LATITUDE TEXT NOT NULL,
    AEROP_LONGITUDE TEXT NOT NULL
);

#--------------------TABELA DE VOOS--------------------

CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,
    VOO_AEROP_DESTINO INT NOT NULL,
    VOO_AERONAVE VARCHAR(10) NOT NULL,
    CONSTRAINT FK_AEROP_ORIGEM FOREIGN KEY(VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AEROP_DESTINO FOREIGN KEY(VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_CODIGO),
    CONSTRAINT FK_AERONAVE FOREIGN KEY(VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

#--------------------TABELA DE EQUIPES--------------------

CREATE TABLE IF NOT EXISTS EQUIPES (
    VOO_ID INT NOT NULL,
    FUNC_ID INT NOT NULL,
    PRIMARY KEY(VOO_ID, FUNC_ID),
    CONSTRAINT VOFU_FK_VOO FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID),
    CONSTRAINT VOFU_FK_FUNCIONARIO FOREIGN KEY(FUNC_ID) REFERENCES FUNCIONARIOS(FUNC_ID)
);

#--------------------TABELA DE RESERVAS--------------------

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    VOO_ID INT NOT NULL,
    PASS_CPF VARCHAR(14) NOT NULL,
    CONSTRAINT FK_PASSAGEIROS FOREIGN KEY(PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOOS FOREIGN KEY(VOO_ID) REFERENCES VOOS(VOO_ID)
);

-- DML'S PARA A TABELA PASSAGEIROS
INSERT INTO PASSAGEIROS (PASS_CPF, PASS_NOME, PASS_TELEFONE, PASS_RUA, PASS_NUMRUA, PASS_BAIRRO, PASS_CIDADE, PASS_ESTADO, PASS_PAIS, PASS_CODPOSTAL, PASS_EMAIL) VALUES ('12345678901', 'Carlos Silva', '(11) 91234-5678', 'Rua das Flores', 123, 'Centro', 'São Paulo', 'SP', 'Brasil', '01000-000', 'carlos.silva@example.com'), ('10987654321', 'Ana Costa', '(21) 98765-4321', 'Avenida Brasil', 456, 'Jardim', 'Rio de Janeiro', 'RJ', 'Brasil', '20000-000', 'ana.costa@example.com'); 
UPDATE PASSAGEIROS SET PASS_EMAIL = 'carlos.novoemail@example.com' WHERE PASS_CPF = '12345678901';

-- DML'S PARA A TABELA FUNCIONARIOS
INSERT INTO FUNCIONARIOS (FUNC_ID, FUNC_CPF, FUNC_NOME, FUNC_DATANASC, FUNC_RUA, FUNC_NUMRUA, FUNC_BAIRRO, FUNC_CIDADE, FUNC_ESTADO, FUNC_PAIS, FUNC_CODPOSTAL) VALUES (1, '12345678901', 'Roberto Almeida', '1985-05-15', 'Rua A', 10, 'Centro', 'Curitiba', 'PR', 'Brasil', '80000-000'), (2, '98765432100', 'Lucia Martins', '1990-08-25', 'Rua B', 20, 'Bela Vista', 'São Paulo', 'SP', 'Brasil', '01010-000'); 
UPDATE FUNCIONARIOS SET FUNC_NOME = 'Roberto A. Almeida' WHERE FUNC_ID = 1;

-- DML'S PARA A TABELA AERONAVES
INSERT INTO AERONAVES (AERON_PREFIXO, AERON_MODELO, AERON_FABRICANTE, AERON_ANOFABR, AERON_CAPACIDADE, AERON_AUTONOMIA) VALUES ('PT-ABC', 'Boeing 737', 'Boeing', 2015, '180', '5000km'), ('PT-XYZ', 'Airbus A320', 'Airbus', 2018, '150', '6000km'); 
UPDATE AERONAVES SET AERON_MODELO = 'Boeing 737 MAX' WHERE AERON_PREFIXO = 'PT-ABC';

-- DML'S PARA A TABELA AEROPORTOS
INSERT INTO AEROPORTOS (AEROP_CODIGO, AEROP_NOME, AEROP_CIDADE, AEROP_PAIS, AEROP_LATITUDE, AEROP_LONGITUDE) VALUES (1, 'Aeroporto de Guarulhos', 'São Paulo', 'Brasil', '-23.4356', '-46.4731'), (2, 'Aeroporto Internacional do Rio de Janeiro', 'Rio de Janeiro', 'Brasil', '-22.8099', '-43.2500'); 
UPDATE AEROPORTOS SET AEROP_NOME = 'Aeroporto Internacional de São Paulo' WHERE AEROP_CODIGO = 1;

-- DML'S PARA A TABELA VOOS
INSERT INTO VOOS (VOO_ID, VOO_DATA, VOO_HORA, VOO_AEROP_ORIGEM, VOO_AEROP_DESTINO, VOO_AERONAVE) VALUES (1, '2024-01-01', '10:00:00', 1, 2, 'PT-ABC'), (2, '2024-01-02', '15:00:00', 2, 1, 'PT-XYZ'); 
UPDATE VOOS SET VOO_HORA = '16:00:00' WHERE VOO_ID = 2;

-- DML'S PARA A TABELA EQUIPES
INSERT INTO EQUIPES (VOO_ID, FUNC_ID) VALUES (1, 1), (2, 2); 
UPDATE EQUIPES SET FUNC_ID = 2 WHERE VOO_ID = 1;

-- DML'S PARA A TABELA RESERVAS
INSERT INTO RESERVAS (RESERVA_COD, VOO_ID, PASS_CPF) VALUES (1, 1, '12345678901'), (2, 2, '10987654321'); 
UPDATE RESERVAS SET PASS_CPF = '98765432100' WHERE RESERVA_COD = 1;
