CREATE SCHEMA SISTEMA_GESTAO_EMPRESARIAL;

USE SISTEMA_GESTAO_EMPRESARIAL;

CREATE TABLE IF NOT EXISTS TIPO_ENDERECO (
	TIPO_END_COD INT PRIMARY KEY,
    TIPO_END_CATEGORIA VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS ENDERECOS (
	END_COD INT PRIMARY KEY,
    END_LOGRADOURO VARCHAR(100) NOT NULL,
    END_NUM VARCHAR(45),
    END_BAIRRO VARCHAR(45) NOT NULL,
    END_CIDADE VARCHAR(45) NOT NULL,
    END_UF CHAR(2) NOT NULL,
    END_CEP VARCHAR(20) NOT NULL,
    -- Chave estrangeira da tabela TIPO_ENDERECO
    TIPO_END_COD INT NOT NULL,
    CONSTRAINT FK_TIPO_ENDERECOS FOREIGN KEY(TIPO_END_COD) REFERENCES TIPO_ENDERECO(TIPO_END_COD)
);

CREATE TABLE IF NOT EXISTS EMPRESAS (
	EMPRE_COD INT PRIMARY KEY,
    EMPRE_CNPJ VARCHAR(45) NOT NULL,
    EMPRE_RAZAOSOCIAL VARCHAR(100) NOT NULL,
    EMPRE_PCONTATO VARCHAR(45) NOT NULL,
    -- Chave estrangeira da tabela ENDERECOS
    EMPRE_END_COD INT NOT NULL UNIQUE,
    CONSTRAINT FK_ENDERECOS FOREIGN KEY(EMPRE_END_COD) REFERENCES ENDERECOS(END_COD)
);


CREATE TABLE IF NOT EXISTS EMPRE_TEL (
	EMPRE_COD INT PRIMARY KEY,
    EMPRE_TEL_TELEFONE VARCHAR(45) NOT NULL,
    -- Chave estrangeira que também é PK da tabela EMPRESAS
    CONSTRAINT FK_EMPRESAS FOREIGN KEY(EMPRE_COD) REFERENCES EMPRESAS(EMPRE_COD) 
);


CREATE TABLE IF NOT EXISTS CLIENTES (
	CLI_COD INT PRIMARY KEY,
    CLI_CNPJ VARCHAR(45) NOT NULL,
    CLI_RAZAOSOCIAL VARCHAR(45) NOT NULL,
    CLI_RAMOATIV VARCHAR(45) NOT NULL,
    CLI_PCONTATO VARCHAR(45) NOT NULL,
    CLI_DATACADAS VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLI_TEL (
	CLI_COD INT PRIMARY KEY,
    CLI_TEL_TELEFONE VARCHAR(45) NOT NULL,
    -- Chave estrangeira que também é PK da tabela CLIENTES
    CONSTRAINT FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD) 
);

-- ENTIDADE ASSOCIATIVA ENTRE CLIENTES <-> ENDERECOS
CREATE TABLE IF NOT EXISTS CLIENTES_ENDERECOS (
	CLI_COD INT NOT NULL,
    CLI_END_COD INT NOT NULL,
	PRIMARY KEY(CLI_COD, CLI_END_COD),
    CONSTRAINT CLEN_FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD),
    CONSTRAINT CLEN_FK_ENDERECOS FOREIGN KEY(CLI_END_COD) REFERENCES ENDERECOS(END_COD)
);

CREATE TABLE IF NOT EXISTS CARGOS (
	CARGOS_COD INT PRIMARY KEY,
    CARGO_NOME VARCHAR(50) NOT NULL,
    CARGO_SALARIO DECIMAL(10,2) NOT NULL
);



CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	FUNC_MATRICULA INT PRIMARY KEY,
    FUNC_NOME VARCHAR(50) NOT NULL,
    FUNC_DATAADMISSAO DATE NOT NULL,
    -- Chave estrangeira da tabela CARGO
    FUNC_CARGO_COD INT NOT NULL,
    -- Chave estangeira da tabela ENDERECOS
    FUNC_END_COD INT NOT NULL,
    CONSTRAINT FUNC_FK_CARGO FOREIGN KEY(FUNC_CARGO_COD) REFERENCES CARGOS(CARGOS_COD),
    CONSTRAINT FUNC_FK_ENDERECOS FOREIGN KEY(FUNC_END_COD) REFERENCES ENDERECOS(END_COD)
);

CREATE TABLE IF NOT EXISTS QUALIFICACOES (
	FUNC_MATRICULA INT PRIMARY KEY,
    QUALIFICACAO_FUNC TEXT,
    CONSTRAINT QUALIFICACOES_FK_FUNC FOREIGN KEY(FUNC_MATRICULA) REFERENCES FUNCIONARIOS(FUNC_MATRICULA)
);

CREATE TABLE IF NOT EXISTS FUNC_TEL (
	FUNC_MATRICULA INT PRIMARY KEY,
    FUNC_TEL VARCHAR(15) NOT NULL,
    CONSTRAINT FUNC_TEL_FK_FUNCIONARIOS FOREIGN KEY(FUNC_MATRICULA) REFERENCES FUNCIONARIOS(FUNC_MATRICULA)
);

CREATE TABLE IF NOT EXISTS ENCOMENDAS (
	ENCOM_COD INT PRIMARY KEY,
    ENCOM_DATAINCLU DATE NOT NULL,
    CLI_COD INT NOT NULL,
    CONSTRAINT ENCOM_FK_CLIENTES FOREIGN KEY(CLI_COD) REFERENCES CLIENTES(CLI_COD)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
	PAG_ID INT PRIMARY KEY,
    PAG_VALORTOTAL DECIMAL(10, 3),
    PAG_VALORDESC DECIMAL(10, 3),
    PAG_VALORLIQ DECIMAL(10, 3),
    PAG_FORMAPAGAMENTO VARCHAR(45) NOT NULL,
    PAG_QTDPARCELAS VARCHAR(45),
    ENCOM_COD INT NOT NULL,
    CONSTRAINT PAG_FK_ENCOMENDAS FOREIGN KEY(ENCOM_COD) REFERENCES ENCOMENDAS(ENCOM_COD)    
);

CREATE TABLE IF NOT EXISTS PRODUTOS (
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(100) NOT NULL,
    PROD_COR VARCHAR(45)  NOT NULL,
    PROD_PESO DECIMAL(10, 2) NOT NULL,
    PROD_PRECOUND DECIMAL(10, 2) NOT NULL,
    PROD_TEMPOFABRI TIME NOT NULL,
    PROD_DESENHOPROD VARCHAR(255) NOT NULL,
    PROD_HRMAOOBRA DECIMAL(10, 2) NOT NULL,
    PROD_ALTURA DECIMAL(10,3) NOT NULL,
    PROD_LARGURA DECIMAL(10,3) NOT NULL,
    PROD_COMPRIMENTO DECIMAL(10,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FORN_COD INT PRIMARY KEY,
    FORN_CNPJ VARCHAR(45) NOT NULL,
    FORN_RAZAOSOCIAL VARCHAR(45) NOT NULL,
    FORN_PCONTATO VARCHAR(45) NOT NULL,
    FORN_END_COD INT NOT NULL,
    CONSTRAINT FORN_FK_ENDERECOS FOREIGN KEY(FORN_END_COD) REFERENCES ENDERECOS(END_COD)
);

CREATE TABLE IF NOT EXISTS TIPO_COMPONENTE (
	TIPO_COMP_COD INT PRIMARY KEY,
    TIPO_COMP_NOME VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPONENTES (
	COMP_COD INT PRIMARY KEY,
    COMP_NOME VARCHAR(45) NOT NULL,
    COMP_QTDESTOQUE INT NOT NULL,
    COMP_PRECOUND DECIMAL(10,2) NOT NULL,
    COMP_UNIDADE INT,
    TIPO_COMP_COD INT NOT NULL,
    -- Chave estrangeira vinda de TIPO_COMPONENTE
    CONSTRAINT COMP_FK_TIPO_COMP FOREIGN KEY(TIPO_COMP_COD) REFERENCES TIPO_COMPONENTE(TIPO_COMP_COD)
);

CREATE TABLE IF NOT EXISTS RS (
	COMPONENTES_COMP_COD INT PRIMARY KEY,
    RS_QUANTIDADE INT NOT NULL,
    RS_DATANESC DATE NOT NULL,
    CONSTRAINT RS_FK_COMPONENTES FOREIGN KEY(COMPONENTES_COMP_COD) REFERENCES COMPONENTES(COMP_COD)
);

-- Tabela associativa de FORNECEDORES <-> COMPONENTES
CREATE TABLE IF NOT EXISTS FORNECEDORES_COMPONENETES (
	COMP_COD INT,
    FORN_COD INT,
    PRIMARY KEY(COMP_COD, FORN_COD),
    CONSTRAINT FOCO_FK_FORNECEDORES FOREIGN KEY(FORN_COD) REFERENCES FORNECEDORES(FORN_COD),
    CONSTRAINT FOCO_FK_COMPONENTES FOREIGN KEY(COMP_COD) REFERENCES COMPONENTES(COMP_COD)
);

CREATE TABLE IF NOT EXISTS MAQUINAS (
	MAQ_ID INT PRIMARY KEY,
	MAQ_TEMPOVIDA TIME NOT NULL,
    MAQ_DATACOMPRA DATE NOT NULL,
    MAQ_FIMGARANTIA DATE NOT NULL
);

 CREATE TABLE IF NOT EXISTS RM (
	RM_DATA DATE PRIMARY KEY,
    RM_DESCRICAO TEXT NOT NULL,
    MAQ_ID INT NOT NULL,
    CONSTRAINT FK_MAQUINAS FOREIGN KEY(MAQ_ID) REFERENCES MAQUINAS(MAQ_ID)
 );
 
 CREATE TABLE IF NOT EXISTS RE (
	RE_COD INT PRIMARY KEY,
    PROD_COD INT NOT NULL,
    FUNC_COD INT NOT NULL,
    MAQ_ID INT NOT NULL,
    COMP_COD INT NOT NULL,
    RE_QTDCOMP INT NOT NULL,
    RE_UNDMEDIDA VARCHAR(45) NOT NULL,
    RE_TEMPOUSOMAQUINA VARCHAR(45) NOT NULL,
    RE_HRMAOOBRA VARCHAR(45),
    CONSTRAINT RE_FK_PRODUTOS FOREIGN KEY(PROD_COD) REFERENCES PRODUTOS(PROD_COD),
    CONSTRAINT RE_FK_FUNCIONARIOS FOREIGN KEY(FUNC_COD) REFERENCES FUNCIONARIOS(FUNC_MATRICULA),
    CONSTRAINT RE_FK_MAQUINAS FOREIGN KEY(MAQ_ID) REFERENCES MAQUINAS(MAQ_ID),
    CONSTRAINT RE_FK_COMPONENTES FOREIGN KEY(COMP_COD) REFERENCES COMPONENTES(COMP_COD)
 );

