CREATE DATABASE IF NOT EXISTS EMPRESA_DE_PASSAGENS_AEREAS;
USE EMPRESA_DE_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    PASS_CPF INT PRIMARY KEY,
    PASS_NOME VARCHAR(30) NOT NULL,
    PASS_TELEFONE VARCHAR(14) NOT NULL,
    PASS_RUA VARCHAR(45) NOT NULL,
    PASS_NUMRUA INT NOT NULL,
    PASS_BAIRRO VARCHAR(45) NOT NULL,
    PASS_CIDADE VARCHAR(45) NOT NULL,
    PASS_ESTADO VARCHAR(45) NOT NULL,
    PASS_CEP DECIMAL(10) NOT NULL,
    PASS_PAIS VARCHAR(30) NOT NULL,
    PASS_EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS (
    AEROP_COD INT PRIMARY KEY,
    AEROP_NOME VARCHAR(30) NOT NULL,
    AEROP_CIDADE VARCHAR(45) NOT NULL,
    AEROP_PAIS VARCHAR(30) NOT NULL,
    AEROP_LATITUDE FLOAT NOT NULL,
    AEROP_LONGITUDE FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES (
    AERON_PREFIXO INT PRIMARY KEY,
    AERON_MODELO VARCHAR(45) NOT NULL,
    AERON_ANOFABR INT NOT NULL,
    AERON_AUTONOMIA VARCHAR(45) NOT NULL,  -- Corrected typo from "NOY" to "NOT"
    AERON_CAPACIDADE INT NOT NULL,
    AERON_FABRICANTE VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    FUNC_ID INT PRIMARY KEY,
    FUNC_NOME VARCHAR(30) NOT NULL,
    FUNC_DATANASC DATE NOT NULL,  -- Corrected "DDATE" to "DATE"
    FUNC_CPF DECIMAL(11,0) NOT NULL,  -- Specify precision for DECIMAL
    FUNC_FUNCAO VARCHAR(30) NOT NULL,
    FUNC_RUA VARCHAR(45) NOT NULL,
    FUNC_CEP DECIMAL(10) NOT NULL,
    FUNC_CIDADE VARCHAR(45) NOT NULL,
    FUNC_BAIRRO VARCHAR(45) NOT NULL,
    FUNC_NUMRUA INT NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS (
    VOO_ID INT PRIMARY KEY,
    VOO_DATA DATE NOT NULL,
    VOO_HORA TIME NOT NULL,
    VOO_AEROP_ORIGEM INT NOT NULL,  -- Changed to INT to reference AEROPORTOS
    VOO_AEROP_DESTINO INT NOT NULL,  -- Changed to INT to reference AEROPORTOS
    VOO_AERONAVE INT NOT NULL,  -- Changed to INT to reference AERONAVES
    CONSTRAINT FK_VOO_ORIGEM FOREIGN KEY (VOO_AEROP_ORIGEM) REFERENCES AEROPORTOS(AEROP_COD),
    CONSTRAINT FK_VOO_DESTINO FOREIGN KEY (VOO_AEROP_DESTINO) REFERENCES AEROPORTOS(AEROP_COD),
    CONSTRAINT FK_VOO_AERONAVE FOREIGN KEY (VOO_AERONAVE) REFERENCES AERONAVES(AERON_PREFIXO)
);

CREATE TABLE IF NOT EXISTS RESERVAS (
    RESERVA_COD INT PRIMARY KEY,
    PASS_CPF INT NOT NULL,
    VOO_ID INT NOT NULL,
    CONSTRAINT FK_PASS_CPF FOREIGN KEY (PASS_CPF) REFERENCES PASSAGEIROS(PASS_CPF),
    CONSTRAINT FK_VOO_ID FOREIGN KEY (VOO_ID) REFERENCES VOOS(VOO_ID)
);

CREATE TABLE IF NOT EXISTS EQUIPES (
    FUVO_FUNCIONARIOS INT,
    FUVO_VOOS INT,
    PRIMARY KEY (FUVO_FUNCIONARIOS, FUVO_VOOS),
    CONSTRAINT FK_FUVO_FUNCIONARIOS FOREIGN KEY (FUVO_FUNCIONARIOS) REFERENCES FUNCIONARIOS(FUNC_ID),
    CONSTRAINT FK_FUVO_VOOS FOREIGN KEY (FUVO_VOOS) REFERENCES VOOS(VOO_ID)
);
