CREATE SCHEMA EST_CASO_V;

USE EST_CASO_V;

CREATE TABLE IF NOT EXISTS CLIENTES (
	CLI_CPF VARCHAR(14) PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_RUA VARCHAR(50),
    CLI_NUMRUA VARCHAR(25) NOT NULL,
    CLI_BAIRRO VARCHAR(50) NOT NULL,
    CLI_CIDADE VARCHAR(50) NOT NULL,
    CLI_UF CHAR(2) NOT NULL,
    CLI_PAIS VARCHAR(100) NOT NULL,
    CLI_CEP VARCHAR(15) NOT NULL,
    CLI_STATUS_PROMO ENUM("APROVADO", "REPROVADO") NOT NULL
);


CREATE TABLE IF NOT EXISTS FORNECEDORES (
	FORN_CNPJ VARCHAR(50) PRIMARY KEY,
    FORN_NOME VARCHAR(100) NOT NULL,
    FORN_TELEFONE VARCHAR(16) NOT NULL,
    FORN_EMAIL VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS PRODUTOS (
	PROD_ID INT PRIMARY KEY,
    PROD_CATEGORIA VARCHAR(50) NOT NULL,
    PROD_QTDDISPONIVEL INT NOT NULL,
	PROD_PRECO DECIMAL(10, 3) NOT NULL
);


CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES (
	PROD_ID INT,
    FORN_CNPJ VARCHAR(50),
    PRIMARY KEY(PROD_ID, FORN_CNPJ),
    CONSTRAINT PRFO_FK_PRODUTOS FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT PRFO_FK_FORNECEDORES FOREIGN KEY(FORN_CNPJ) REFERENCES FORNECEDORES(FORN_CNPJ)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
	PAG_ID INT PRIMARY KEY,
    PAG_DATA DATE NOT NULL,
    PAG_HORA TIME NOT NULL,
    PAG_VALOR DECIMAL (10,3) NOT NULL,
    PAG_STATUS ENUM("PENDENTE", "PAGO", "CANCELADO")
);

CREATE TABLE IF NOT EXISTS VENDAS (
	VENDA_ID INT PRIMARY KEY,
    CLI_CPF VARCHAR(14) NOT NULL,
    PAG_ID INT NOT NULL,
    CONSTRAINT VENDA_FK_CLIENTES FOREIGN KEY(CLI_CPF) REFERENCES CLIENTES(CLI_CPF),
    CONSTRAINT VENDA_FK_PAGAMENTOS FOREIGN KEY(PAG_ID) REFERENCES PAGAMENTOS(PAG_ID)
);

CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS (
	VENDA_ID INT,
    PROD_ID INT,
    PRIMARY KEY(VENDA_ID, PROD_ID),
    VEPRO_QTD_VENDIDA INT NOT NULL,
    VEPRO_VALORTOTAL DECIMAL(10,3) NOT NULL,
    CONSTRAINT VEPRO_FK_PRODUTOS FOREIGN KEY(PROD_ID) REFERENCES PRODUTOS(PROD_ID),
    CONSTRAINT VEPRO_FK_VENDAS FOREIGN KEY(VENDA_ID) REFERENCES VENDAS(VENDA_ID)
);
